// Central mutable application state. Every other module imports the
// `state` object and reads/writes its properties directly — the app has
// no framework-level reactivity, so views re-render explicitly via render().
export var state = {
  persons: [],
  entries: [],
  places: [],
  books: [],
  bookCandidates: [],
  researchJobs: [],
  aiRuns: [],
  personImages: [],
  tableAvailability: {},
  view: 'status',
  profilePerson: null,
  fil: {},
  profileEdit: false,
  fitPanelExpanded: false,
  personSort: 'next',
  personRenderLimit: 30,
  bookPages: [],
  layoutState: { view: 'list', page: null, selectedBlockId: null, saveStatus: 'saved' },
  layoutPresetPersonId: null,
  enhanceState: { phase: 'idle', personName: '', data: null, error: '' },
  addState: { phase: 'input', person: null, entries: [], prefill: '', job: null, usage: null, mode: 'capture' },
  captureBusy: false,
  profileTab: 'overview',
  profileEntryFilter: null,
  dashboardQueue: [],
  dashboardQueueLimit: 10,
  pilotQueueLimit: 12,
  queueResumeBusy: false,
  blockUndoSnapshot: null,
  pageSaveTimer: null,
  pageSaveInFlight: false,
  pageSavePending: false,
  personsSearchBeforeProfile: '',
  personsScrollBeforeProfile: 0,
  filterPanelsOpen: {},
};
