import { addEntry, captureName, changeEntryKat, removeEntry, resetAdd, saveData } from './add.js';
import { addBlock, deleteBlock, pickEntryForBlock, setBlockContent, setBlockImage, setBlockStyle, undoLastBlockChange } from './pages/editor.js';
import { applyPageTemplate } from './pages/templates.js';
import { backToPersons, closeMoreMenu, expandFitPanel, goTab, init, openCapture, render, setPersonSort, toggleMoreMenu } from './state/router.js';
import { state } from './state/store.js';
import { openResearchJob } from './views/dashboard.js';
import { applyEnhanceSuggestions, cancelEnhance, startEnhance, startExpand } from './views/enhance.js';
import { backToPageList, createNewPage, deletePage, duplicatePage, openAdjacentPage, openPageEditor, renamePage } from './views/pages.js';
import { addToPilot, savePilotFit } from './views/pilot.js';
import { addPersonImageFromFile, addPersonImageFromUrl, cancelProfileEdit, editProfile, moreResearch, removePersonImage, saveProfileEdit, setCoverImage } from './views/profile.js';

// Inline HTML event-handler attributes (onclick="…") execute in global
// scope, not module scope, so every function referenced that way needs an
// explicit bridge onto window. Real cross-module calls all go through
// normal import/export above — this bridge exists only for the HTML
// strings generated by the render functions.
window.addBlock = addBlock;
window.addEntry = addEntry;
window.addPersonImageFromFile = addPersonImageFromFile;
window.addPersonImageFromUrl = addPersonImageFromUrl;
window.addToPilot = addToPilot;
window.applyEnhanceSuggestions = applyEnhanceSuggestions;
window.applyPageTemplate = applyPageTemplate;
window.backToPageList = backToPageList;
window.backToPersons = backToPersons;
window.cancelEnhance = cancelEnhance;
window.cancelProfileEdit = cancelProfileEdit;
window.captureName = captureName;
window.changeEntryKat = changeEntryKat;
window.createNewPage = createNewPage;
window.deleteBlock = deleteBlock;
window.deletePage = deletePage;
window.duplicatePage = duplicatePage;
window.editProfile = editProfile;
window.expandFitPanel = expandFitPanel;
window.goTab = goTab;
window.moreResearch = moreResearch;
window.openAdjacentPage = openAdjacentPage;
window.openCapture = openCapture;
window.openPageEditor = openPageEditor;
window.openResearchJob = openResearchJob;
window.pickEntryForBlock = pickEntryForBlock;
window.removeEntry = removeEntry;
window.removePersonImage = removePersonImage;
window.renamePage = renamePage;
window.render = render;
window.resetAdd = resetAdd;
window.saveData = saveData;
window.savePilotFit = savePilotFit;
window.saveProfileEdit = saveProfileEdit;
window.setBlockContent = setBlockContent;
window.setBlockImage = setBlockImage;
window.setBlockStyle = setBlockStyle;
window.setCoverImage = setCoverImage;
window.setPersonSort = setPersonSort;
window.startEnhance = startEnhance;
window.startExpand = startExpand;
window.toggleMoreMenu = toggleMoreMenu;
window.undoLastBlockChange = undoLastBlockChange;

document.addEventListener('click', closeMoreMenu);
document.addEventListener('keydown', function(e) {
  if (e.key === '/' && document.activeElement.tagName !== 'INPUT') {
    e.preventDefault();
    document.getElementById('srch').focus();
  }
  if (e.key === 'Escape' && state.view === 'profile') backToPersons();
});
init();
